### PR TITLE
Upgrade to Camel 2.17

### PR DESCRIPTION
**Pull request by apupier**

### CODE REVIEW

**Comment by oscerd** [comment]
@apupier we released 2.17.1 in the last weeks :-)

**Comment by apupier** [comment]
@oscerd which version should I use then? 2.17.1 for parent and 2.17.1.redhat-???

**Comment by apupier** [comment]
@oscerd BTW, how do you modify all paren tpom version for other projects? Is it manually? or is there a script? the idea is to include the modification automatically also on this fuse component.

**Comment by oscerd** [comment]
Actually I think it is better to stay on 2.17.0 for parent and 2.17.0-redhat. I don't know so much about camel-SAP, but the parent version seems to come from the community.

When we release, the version is automatically updated inside all the Community components etc... Camel-SAP is outside this mechanism.. The only way I see to update automatically the dependency is through some jenkins job, like in fabric8 for example:

https://github.com/fabric8io/fabric8/blob/master/release.groovy#L5

**Pull request merged**
