### PR TITLE
ENTESB-14485 backport the fixes to the 6.3.0

### PR DESCRIPTION
**Pull request by zhfeng**
https://issues.redhat.com/browse/ENTESB-14485

### CODE REVIEW

**Comment by zhfeng** [comment]
@cunningt can you take a review ?

**Review by grgrzybek — COMMENTED** [review]
@zhfeng I see mixed versions 3.1.0/3.1.2 for jco/idoc libraries - if you confirm it's ok, I'll approve ;)

**Comment by zhfeng** [comment]
Thanks @grgrzybek and these are OK, I can confirm !

**Review by grgrzybek — APPROVED** [review]
Thanks!

**Pull request merged**
