### PR TITLE
upgrade to sapjco 3.1.2 and sapjidoc 3.1.0

### PR DESCRIPTION
**Pull request by zhfeng**
DON'T MERGE until the new version of the sapjco and sapjidoc are avaiable in the internal repo

### CODE REVIEW

**Comment by zhfeng** [comment]
Since the lastest  version have been avaiable in the repo now, I'd like to merge these changes. Thanks @djcoleman and can you review and approve this PR ?

**Comment by djcoleman** [comment]
Hi,
I think a couple of the modules haven't been updated:
- https://github.com/zhfeng/fuse-components/blob/ENTESB-14453/camel-sap/com.sap.conn.jco.win32.x86/pom.xml#L70 - the version needs to be changed.
- https://github.com/zhfeng/fuse-components/blob/ENTESB-14453/camel-sap/com.sap.conn.jco.osx.x86_64/pom.xml#L88 - the version needs to be changed, and also the type/file-extension has changed from jnilib to dylib, for some reason.

**Comment by zhfeng** [comment]
Thanks for the reviewing and I just commit to fix them.

**Review by djcoleman — APPROVED** [review]

**Comment by zhfeng** [comment]
Thanks @djcoleman !

**Pull request merged**
